// PLACEHOLDER — not a real Firebase configuration.
//
// This file is normally generated by running `flutterfire configure` from
// `apps/mobile/` against a real Firebase project (see
// docs/FIREBASE_SETUP.md, section 1, steps 3-5). That requires a Google
// account with access to the Firebase console and cannot be done from
// inside this coding sandbox.
//
// Until someone runs the real `flutterfire configure`, every value below is
// obviously fake. `main.dart` wraps `Firebase.initializeApp` in a try/catch
// specifically so this placeholder fails to initialize *quietly* — the app
// falls back to the console-OTP login flow (`send-otp`/`verify-otp`, see
// `docs/SECURITY.md`) instead of crashing on startup. Once the real file is
// generated, it should replace this one wholesale and Firebase Phone Auth
// (`docs/FIREBASE_SETUP.md`) starts working automatically — no other code
// change is required.
//
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// PLACEHOLDER: regenerate with `flutterfire configure` (see
/// docs/FIREBASE_SETUP.md) before relying on this in a real build.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform. '
          'Run `flutterfire configure` per docs/FIREBASE_SETUP.md.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
    appId: '1:000000000000:web:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
    authDomain: 'replace-with-flutterfire-configure.firebaseapp.com',
    storageBucket: 'replace-with-flutterfire-configure.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
    appId: '1:000000000000:android:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
    storageBucket: 'replace-with-flutterfire-configure.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
    appId: '1:000000000000:ios:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
    storageBucket: 'replace-with-flutterfire-configure.appspot.com',
    iosBundleId: 'tj.tajikshop.app',
  );
}
